name: Linting and Push on Approval

on:
  pull_request:  # Trigger on pull requests
  push:
    paths:
      - 'approved'  # Trigger on changes to 'approved'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        id: lint  # Assign an ID to the linter step
        run: npm run lint
        env:
          CI: true

      - name: Push to another repository (if 'approved' changed and linting passed)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'approved') && steps.lint.outcome == 'success' }}
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"
          git remote add target https://${{ secrets.ACCESS_TOKEN }}@github.com/username/target-repository.git
          git push target main
